from __future__ import annotations

import hashlib
import os
import re
import secrets
import stat
from pathlib import Path
from typing import BinaryIO
from uuid import UUID

from app.storage.base import ReconciliationReport


_STORAGE_KEY_PATTERN = re.compile(
    r"\Aobjects/(?P<first>[0-9a-f]{2})/(?P<second>[0-9a-f]{2})/"
    r"(?P<identifier>[0-9a-f]{32})\Z"
)
_NOFOLLOW = getattr(os, "O_NOFOLLOW", 0)
_NONBLOCK = getattr(os, "O_NONBLOCK", 0)


class StorageError(RuntimeError):
    """Base error for private asset storage."""


class StorageKeyError(StorageError):
    """A storage key was not generated by this implementation."""


class StorageObjectExistsError(StorageError):
    """Atomic finalization refused to overwrite an existing object."""


class StorageObjectMissingError(StorageError):
    """An active database object has no readable local file."""


class StorageObjectUnsafeError(StorageError):
    """A storage node is not a regular, application-owned file."""


class _LocalStagedWrite:
    def __init__(
        self,
        storage: LocalAssetStorage,
        asset_id: UUID,
        staging_path: Path,
        descriptor: int,
    ) -> None:
        self._storage = storage
        self._asset_id = asset_id
        self._staging_path = staging_path
        self._descriptor: int | None = descriptor
        self._hash = hashlib.sha256()
        self._byte_size = 0
        self._finalized = False

    @property
    def byte_size(self) -> int:
        return self._byte_size

    @property
    def content_sha256(self) -> str:
        return self._hash.hexdigest()

    def write(self, chunk: bytes) -> None:
        if self._descriptor is None or self._finalized:
            raise StorageError("staged asset is no longer writable")
        if not isinstance(chunk, bytes):
            raise TypeError("asset chunks must be bytes")
        view = memoryview(chunk)
        while view:
            written = os.write(self._descriptor, view)
            if written <= 0:  # pragma: no cover - defensive OS contract guard
                raise StorageError("asset storage write made no progress")
            view = view[written:]
        self._hash.update(chunk)
        self._byte_size += len(chunk)

    def finalize(self) -> str:
        if self._descriptor is None or self._finalized:
            raise StorageError("staged asset cannot be finalized")
        descriptor = self._descriptor
        os.fsync(descriptor)
        os.close(descriptor)
        self._descriptor = None

        key = self._storage.key_for(self._asset_id)
        destination = self._storage.path_for(key)
        self._storage._ensure_object_parent(destination)
        try:
            os.link(
                self._staging_path,
                destination,
                src_dir_fd=None,
                dst_dir_fd=None,
                follow_symlinks=False,
            )
        except FileExistsError as exc:
            raise StorageObjectExistsError("asset object already exists") from exc
        try:
            os.chmod(destination, 0o600, follow_symlinks=False)
            self._staging_path.unlink()
            self._storage._fsync_directory(destination.parent)
            self._storage._fsync_directory(self._storage.staging_root)
        except BaseException:
            try:
                destination.unlink()
            except FileNotFoundError:
                pass
            raise
        self._finalized = True
        return key

    def abort(self) -> None:
        descriptor = self._descriptor
        self._descriptor = None
        if descriptor is not None:
            os.close(descriptor)
        try:
            self._staging_path.unlink()
        except FileNotFoundError:
            pass


class LocalAssetStorage:
    """Private local storage with generated keys and atomic no-overwrite publish."""

    def __init__(self, root: Path) -> None:
        if not isinstance(root, Path):
            root = Path(root)
        if not root.is_absolute():
            raise ValueError("asset storage root must be absolute")
        unresolved = root.absolute()
        resolved = root.resolve(strict=False)
        if unresolved != resolved:
            raise ValueError("asset storage root must not traverse symlinks")

        root.mkdir(mode=0o700, parents=True, exist_ok=True)
        self._validate_directory(root)
        os.chmod(root, 0o700)
        self.root = root
        self.staging_root = root / ".staging"
        self.quarantine_root = root / ".quarantine"
        self.objects_root = root / "objects"
        for directory in (
            self.staging_root,
            self.quarantine_root,
            self.objects_root,
        ):
            directory.mkdir(mode=0o700, exist_ok=True)
            self._validate_directory(directory)
            os.chmod(directory, 0o700)

    @staticmethod
    def key_for(asset_id: UUID) -> str:
        if not isinstance(asset_id, UUID):
            raise TypeError("asset_id must be a UUID")
        identifier = asset_id.hex
        return f"objects/{identifier[:2]}/{identifier[2:4]}/{identifier}"

    def path_for(self, storage_key: str) -> Path:
        match = _STORAGE_KEY_PATTERN.fullmatch(storage_key)
        if match is None:
            raise StorageKeyError("invalid generated asset storage key")
        identifier = match.group("identifier")
        if (
            match.group("first") != identifier[:2]
            or match.group("second") != identifier[2:4]
        ):
            raise StorageKeyError("invalid generated asset storage key")
        path = self.root.joinpath(*storage_key.split("/"))
        if self.root not in path.parents:
            raise StorageKeyError("asset storage key escapes configured root")
        return path

    def begin_write(self, asset_id: UUID) -> _LocalStagedWrite:
        self.key_for(asset_id)
        try:
            self._validate_directory(self.staging_root)
        except (OSError, ValueError) as exc:
            raise StorageObjectUnsafeError("asset staging directory is unsafe") from exc
        name = f"{asset_id.hex}.{secrets.token_hex(16)}.tmp"
        staging_path = self.staging_root / name
        descriptor = os.open(
            staging_path,
            os.O_WRONLY | os.O_CREAT | os.O_EXCL | _NOFOLLOW,
            0o600,
        )
        return _LocalStagedWrite(self, asset_id, staging_path, descriptor)

    def open_read(self, storage_key: str) -> BinaryIO:
        path = self.path_for(storage_key)
        try:
            self._validate_object_ancestors(path)
            details = path.lstat()
            if not stat.S_ISREG(details.st_mode):
                raise StorageObjectUnsafeError(
                    "asset object is not a regular file"
                )
        except FileNotFoundError as exc:
            raise StorageObjectMissingError("asset object is unavailable") from exc
        except StorageObjectUnsafeError:
            raise
        except (OSError, ValueError) as exc:
            raise StorageObjectUnsafeError("asset object is unsafe") from exc
        try:
            descriptor = os.open(path, os.O_RDONLY | _NOFOLLOW)
        except FileNotFoundError as exc:
            raise StorageObjectMissingError("asset object is unavailable") from exc
        except OSError as exc:
            raise StorageObjectUnsafeError("asset object is unsafe") from exc
        try:
            details = os.fstat(descriptor)
            if not stat.S_ISREG(details.st_mode) or details.st_nlink < 1:
                raise StorageObjectUnsafeError("asset object is not a regular file")
            return os.fdopen(descriptor, "rb", closefd=True)
        except BaseException:
            os.close(descriptor)
            raise

    def delete(self, storage_key: str) -> bool:
        path = self.path_for(storage_key)
        try:
            details = path.lstat()
        except FileNotFoundError:
            return False
        try:
            self._validate_object_ancestors(path)
        except (OSError, ValueError) as exc:
            raise StorageObjectUnsafeError("asset object is unsafe") from exc
        if not stat.S_ISREG(details.st_mode):
            raise StorageObjectUnsafeError("asset object is not a regular file")
        path.unlink()
        self._fsync_directory(path.parent)
        return True

    def reconcile(
        self,
        *,
        active_keys: set[str] | None,
        deleted_keys: set[str],
    ) -> ReconciliationReport:
        removed_staging = 0
        removed_deleted = 0
        quarantined_unknown = 0
        unexpected: list[str] = []

        try:
            for directory in (
                self.root,
                self.staging_root,
                self.quarantine_root,
                self.objects_root,
            ):
                self._validate_directory(directory)
        except (OSError, ValueError) as exc:
            raise StorageObjectUnsafeError(
                "asset storage root contains an unsafe directory"
            ) from exc

        for entry in self.staging_root.iterdir():
            details = entry.lstat()
            if stat.S_ISREG(details.st_mode):
                entry.unlink()
                removed_staging += 1
            else:
                unexpected.append(entry.name)

        for key in deleted_keys:
            try:
                if self.delete(key):
                    removed_deleted += 1
            except (StorageKeyError, StorageObjectUnsafeError):
                unexpected.append(key)

        if active_keys is not None:
            known = active_keys | deleted_keys
            for path in self._iter_object_paths(unexpected):
                relative = path.relative_to(self.root).as_posix()
                try:
                    self.path_for(relative)
                except StorageKeyError:
                    unexpected.append(relative)
                    continue
                details = path.lstat()
                if not stat.S_ISREG(details.st_mode):
                    unexpected.append(relative)
                    continue
                if relative not in known:
                    self._quarantine(path)
                    quarantined_unknown += 1

        missing_active = tuple(
            sorted(
                key
                for key in (active_keys or set())
                if not self._is_safe_object(key)
            )
        )
        return ReconciliationReport(
            removed_staging=removed_staging,
            removed_deleted=removed_deleted,
            quarantined_unknown=quarantined_unknown,
            missing_active=missing_active,
            unexpected_nodes=tuple(sorted(unexpected)),
        )

    def _iter_object_paths(self, unexpected: list[str]) -> tuple[Path, ...]:
        try:
            self._validate_directory(self.objects_root)
        except (OSError, ValueError):
            unexpected.append("objects")
            return ()

        paths: list[Path] = []
        for first in self.objects_root.iterdir():
            first_relative = first.relative_to(self.root).as_posix()
            try:
                self._validate_directory(first)
            except (OSError, ValueError):
                unexpected.append(first_relative)
                continue
            for second in first.iterdir():
                second_relative = second.relative_to(self.root).as_posix()
                try:
                    self._validate_directory(second)
                except (OSError, ValueError):
                    unexpected.append(second_relative)
                    continue
                paths.extend(second.iterdir())
        return tuple(paths)

    def _is_safe_object(self, storage_key: str) -> bool:
        try:
            path = self.path_for(storage_key)
            self._validate_object_ancestors(path)
            return stat.S_ISREG(path.lstat().st_mode)
        except (StorageError, OSError, ValueError):
            return False

    def _quarantine(self, path: Path) -> None:
        self._validate_object_ancestors(path)
        self._validate_directory(self.quarantine_root)
        destination = self.quarantine_root / path.name
        if destination.exists():
            destination = self.quarantine_root / (
                f"{path.name}.{secrets.token_hex(8)}"
            )
        os.link(path, destination, follow_symlinks=False)
        os.chmod(destination, 0o600, follow_symlinks=False)
        path.unlink()
        self._fsync_directory(self.quarantine_root)
        self._fsync_directory(path.parent)

    def _ensure_object_parent(self, destination: Path) -> None:
        try:
            relative_parts = destination.relative_to(self.objects_root).parts
            if len(relative_parts) != 3:
                raise ValueError("asset destination has an invalid shape")
            self._validate_directory(self.root)
            self._validate_directory(self.objects_root)
            first = self.objects_root / relative_parts[0]
            first.mkdir(mode=0o700, exist_ok=True)
            self._validate_directory(first)
            os.chmod(first, 0o700)
            second = first / relative_parts[1]
            second.mkdir(mode=0o700, exist_ok=True)
            self._validate_directory(second)
            os.chmod(second, 0o700)
            if second != destination.parent:
                raise ValueError("asset destination has an invalid parent")
        except (OSError, ValueError) as exc:
            raise StorageObjectUnsafeError("asset object directory is unsafe") from exc

    def _validate_object_ancestors(self, path: Path) -> None:
        relative_parts = path.relative_to(self.objects_root).parts
        if len(relative_parts) != 3:
            raise ValueError("asset object has an invalid shape")
        self._validate_directory(self.root)
        self._validate_directory(self.objects_root)
        first = self.objects_root / relative_parts[0]
        self._validate_directory(first)
        second = first / relative_parts[1]
        self._validate_directory(second)
        if second != path.parent:
            raise ValueError("asset object has an invalid parent")

    @staticmethod
    def _validate_directory(path: Path) -> None:
        details = path.lstat()
        if not stat.S_ISDIR(details.st_mode) or path.is_symlink():
            raise ValueError("asset storage directories must be real directories")

    @staticmethod
    def _fsync_directory(path: Path) -> None:
        descriptor = os.open(path, os.O_RDONLY | _NOFOLLOW)
        try:
            os.fsync(descriptor)
        finally:
            os.close(descriptor)
